module.exports = {
  checked: '✔️',
  diner: '🍽',
  gift: '🎁',
  guests: '👥',
  menu: {
    allergen: '🍴❕',
    children: '🧒🍟',
    other: '🍴❔',
    standard: '🐟🥩',
    vegan: '🥦🥕',
    vegetarian: '🥚🥗',
  },
  money: '💰',
  music: '🎵',
  profile: {
    female: '👰',
    male: '🤵',
    heart: '❤️',
    both: '🤩',
    party: '🥳',
    cat: '🐱',
    dog: '🐶',
    horse: '🐴',
    monkey: '🐵',
    unicorn: '🦄',
  },
  tag: '🏷️',
}
