export const guests = [
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Leanne Graham",
        "relative": 1,
        "menu": "standard",
        "assistance": "pending",
        "tags": "work,gym",
        "presents": "",
        "seat": "",
        "email": "leanne.graham@guests.com",
        "phone": "695847586"
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Ervin Howell",
        "email": "ervin.howell@guests.com",
        "phone": "695847586",
        "menu": "vegetarian",
        "relative": 0,
        "tags": "common-1,gym",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Clementine Bauch",
        "menu": "children",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Patricia Lebsack",
        "email": "patricia.lebsack@guests.com",
        "phone": "695847586",
        "menu": "other",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Chelsey Dietrich",
        "email": "chelsey.dietrich@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "friends-1,friends-2",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Mrs. Dennis Schulist",
        "email": "dennis.schulist@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "friends-1,childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Kurtis Weissnat",
        "email": "kurtis.weissnat@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 0,
        "tags": "common-1,childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Nicholas Runolfsdottir",
        "email": "nicholas.runolfsdottir@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "work,childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Glenna Reichert",
        "email": "glenna.reichert@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "work,childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Clementina DuBuque",
        "email": "clementina.duBuque@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "work",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Antonio Fernández",
        "email": "antonio.fernandez@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "gym",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Linda Watson",
        "email": "linda.watson@guests.com",
        "phone": "695847586",
        "menu": "vegetarian",
        "relative": 0,
        "tags": "common-1,gym",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Macaulay Culkin",
        "menu": "children",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Liam Wong",
        "email": "liam.wong@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family,gym",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "María Valverde",
        "email": "maria.valverde@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "friends-1,friends-2",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Nuria Díaz",
        "email": "nuria.diaz@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "friends-1,childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Víctor Robles",
        "email": "victor.robles@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 0,
        "tags": "common-1,childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Íker Morán",
        "email": "iker.moran@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Álvaro Méndez",
        "email": "alvaro.mendez@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Adrian Veidt",
        "email": "adrian.veidt@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Paco Iglesias",
        "email": "Paco.iglesias@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "work",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Ignatius Farray",
        "email": "ignatius.farray@guests.com",
        "phone": "695847586",
        "menu": "vegetarian",
        "relative": 0,
        "tags": "common-1",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "David Broncano",
        "menu": "children",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Héctor de Miguel",
        "email": "hector.demiguel@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Elon Musk",
        "email": "elon.musk@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "friends-1,friends-2",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Richard Hendricks",
        "email": "richard.hendricks@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "friends-1,childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Erlich Bachman",
        "email": "erlich.bachman@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 0,
        "tags": "common-1",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Ana Pastor",
        "email": "ana.pastor@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "work",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Sandra Sabatés",
        "email": "sandra.sabatés@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Cristina Mendoza",
        "email": "cristina.mendoza@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "work",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Manuela Carmena",
        "email": "manuela.carmena@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "work",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Nacho Ares",
        "email": "nacho.ares@guests.com",
        "phone": "695847586",
        "menu": "vegetarian",
        "relative": 0,
        "tags": "gym",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Tom Walker",
        "menu": "children",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Rachel Green",
        "email": "rachel.green@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Johnny Huertas",
        "email": "johnny.huertas@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "friends-1,friends-2",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Anthony Caballero",
        "email": "anthony.caballero@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "friends-1,childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Rafa Mariscal",
        "email": "rafa.mariscal@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 0,
        "tags": "common-2",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Cisne de Utrera",
        "email": "cisne.deutrera@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Ángela Rodríguez",
        "email": "angela.rodriguez@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Naomi Klein",
        "email": "naomi.klein@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "work",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },










    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Busta Rhymes",
        "relative": 2,
        "tags": "neighbour",
        "menu": "standard",
        "assistance": "yes",
        "presents": "",
        "seat": "",
        "email": "busta.rhymes@guests.com",
        "phone": "695847586",
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Óscar Sánchez",
        "email": "oscar.sanchez@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 0,
        "tags": "common-2",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Bob Dylan",
        "email": "oscar.sanchez@guests.com",
        "menu": "children",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Luis Suárez",
        "email": "luis.suarez@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Tom Hardy",
        "email": "tom.hardy@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "friends-1,friends-3",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Pablo Inglesias",
        "email": "pablo.iglesias@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "friends-3,childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Kurt Cobain",
        "email": "kurt.cobain@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 0,
        "tags": "common-1,childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Nicolás Rubio",
        "email": "nicolas.rubio@guests.com",
        "phone": "695847586",
        "menu": "children",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Gerardo Ruiz",
        "email": "gerardo.ruiz@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "work,childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Luisa Martínez",
        "email": "luisa.martinez@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Antonio Díaz",
        "email": "antonio.diaz@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Andy Watson",
        "email": "andy.watson@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 0,
        "tags": "common-3",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Bob Sponge",
        "email": "bob.sponge@guests.com",
        "menu": "children",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Liam Neeson",
        "email": "liam.neeson@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "María Ríos",
        "email": "maria.rios@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "friends-3,friends-2",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Nuria Méndez",
        "email": "nuria.mendez@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Víctor Conde",
        "email": "victor.conde@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 0,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Íker Casillas",
        "email": "iker.casillas@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Álvaro Vázquez",
        "email": "alvaro.vazquez@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Adrian Brody",
        "email": "adrian.brody@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": ["Paint"],
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Paco Tous",
        "email": "Paco.tous@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Nacho Juárez",
        "email": "nacho.juarez@guests.com",
        "phone": "695847586",
        "menu": "vegetarian",
        "relative": 0,
        "tags": "family",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "David Prieto",
        "email": "david.prieto@guests.com",
        "menu": "children",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Alberto Randi",
        "email": "alberto.randi@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": ["Song"],
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Elías Cortés",
        "email": "elias.cortes@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Ricardo Martín",
        "email": "ricardo.martin@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Miguel Hernández",
        "email": "miguel.hernandez@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 0,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Ana Linares",
        "email": "ana.linares@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Beatriz Saavedra",
        "email": "beatriz.saavedra@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Cristian Mendoza",
        "email": "cristian.mendoza@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Noemí Padilla",
        "email": "noemi.padilla@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Nacho Arias",
        "email": "nacho.arias@guests.com",
        "phone": "695847586",
        "menu": "vegetarian",
        "relative": 0,
        "tags": "family",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "John Walker",
        "email": "john.walker@guests.com",
        "menu": "children",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Linda Green",
        "email": "linda.green@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "antonio Huertas",
        "email": "antonio.huertas@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Anthony Cano",
        "email": "anthony.cano@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Rafa Infante",
        "email": "rafa.infante@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 0,
        "tags": "common-3",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Carlos Esteban",
        "email": "carlos.esteban@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "José Rodríguez",
        "email": "jose.rodriguez@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Naomi Campbell",
        "email": "naomi.campbell@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },










    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Luis Ramírez",
        "email": "luis.ramirez@guests.com",
        "relative": 2,
        "tags": "family",
        "menu": "standard",
        "assistance": "pending",
        "presents": "",
        "seat": "",
        "phone": "695847586",
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Melwin Lin",
        "email": "melwin.lin@guests.com",
        "phone": "695847586",
        "menu": "vegetarian",
        "relative": 0,
        "tags": "common-3",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Carlos Santiago",
        "email": "carlos.santiago@guests.com",
        "menu": "children",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Patricia Conde",
        "email": "patricia.conde@guests.com",
        "phone": "695847586",
        "menu": "allergen",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Mónica Limón",
        "email": "monica.limon@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "friends-1,friends-2",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Antonio Limones",
        "email": "antonio.limones@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "friends-3,childhood",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Kurtis Klaus",
        "email": "kurtis.klaus@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 0,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Jackson Teller",
        "email": "jackson.teller@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Clay Morrow",
        "email": "clay.morrow@guests.com",
        "phone": "695847586",
        "menu": "vegan",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Gema Casas",
        "email": "gema.casas@guests.com",
        "phone": "695847586",
        "menu": "vegan",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "María Santiago",
        "email": "maria.santiago@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Mandy Watson",
        "email": "mandy.watson@guests.com",
        "phone": "695847586",
        "menu": "vegetarian",
        "relative": 0,
        "tags": "family",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Mona Lisa",
        "email": "mona.lisa@guests.com",
        "menu": "children",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Chan Wong",
        "email": "chan.wong@guests.com",
        "phone": "695847586",
        "menu": "vegan",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Zatu Rey",
        "email": "maria.valverde@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Tote King",
        "email": "tote.king@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Kase O",
        "email": "kase.o@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 0,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Íker Albarreal",
        "email": "iker.albarreal@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Álvaro Castillo",
        "email": "alvaro.castillo@guests.com",
        "phone": "695847586",
        "menu": "vegan",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Adriana Ferraz",
        "email": "adriana.ferraz@guests.com",
        "phone": "695847586",
        "menu": "vegan",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Francisco Hernández",
        "email": "francisco.hernandez@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Fran Navarro",
        "email": "fran.navarro@guests.com",
        "phone": "695847586",
        "menu": "vegetarian",
        "relative": 0,
        "tags": "common-1",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "David Páez",
        "email": "david.paez@guests.com",
        "menu": "children",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Héctor Sánchez",
        "email": "hector.sanchez@guests.com",
        "phone": "695847586",
        "menu": "vegan",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Abel Nuñez",
        "email": "abel.nunez@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Gonzalo González",
        "email": "richard.hendricks@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Eusebio Singular",
        "email": "eusebio.singular@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 0,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Ana Duarte",
        "email": "ana.duarte@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Luis Sabatés",
        "email": "luis.sabatés@guests.com",
        "phone": "695847586",
        "menu": "vegan",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Cristina Saavedra",
        "email": "cristina.saavedra@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Manuel Carballo",
        "email": "manuel.carballo@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Ignacio Arias",
        "email": "ignacio.arias@guests.com",
        "phone": "695847586",
        "menu": "vegetarian",
        "relative": 0,
        "tags": "common-2",
        "assistance": "pending",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Tom Hanks",
        "email": "tom.hanks@guests.com",
        "menu": "children",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Raquel Verde",
        "email": "raquel.verde@guests.com",
        "phone": "695847586",
        "menu": "vegan",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Johnny Camas",
        "email": "johnny.camas@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Antonio Alcántara",
        "email": "antonio.alcantara@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Ángel Hernández",
        "email": "angel.hernandez@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 0,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Faraón de Las Letanías",
        "email": "faraon.delasletanias@guests.com",
        "phone": "695847586",
        "menu": "standard",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Rafael Rodríguez",
        "email": "rafael.rodriguez@guests.com",
        "phone": "695847586",
        "menu": "vegan",
        "relative": 1,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    },
    {
        "weddingId": "5e95863fd5a0591f94dbca10",
        "fullName": "Daniel L. Jackson",
        "email": "daniel.ljackson@guests.com",
        "phone": "695847586",
        "menu": "vegan",
        "relative": 2,
        "tags": "family",
        "assistance": "yes",
        "presents": "",
        "seat": ""
    }
];
